export const productsData = [
  {
    id: 1,
    name: "brocoli",
    image: "/img/products/product-1.jpg",
    price: 100,
    discount: { amount: 50 },
    shortDescription:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Delectus rerum dolore, amet vel eveniet expedita aperiam optio quos maiores fugiat ab placeat sequi? Neque veniam tempora mollitia porro, quae nostrum.",
    rating: 2,
    category_id: 1,
  },
  {
    id: 2,
    name: "tomato",
    image: "/img/products/product-2.jpg",
    price: 13,
    discount: { percent: 20 },
    shortDescription:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Delectus rerum dolore, amet vel eveniet expedita aperiam optio quos maiores fugiat ab placeat sequi? Neque veniam tempora mollitia porro, quae nostrum.",
    rating: 5,
    category_id: 1,
  },
  {
    id: 3,
    name: "pepper",
    image: "/img/products/product-3.jpg",
    price: 200,
    rating: 4,
    category_id: 1,
  },
  {
    id: 4,
    name: "banana",
    image: "/img/products/product-4.jpg",
    price: 500,
    discount: { amount: 220 },
    rating: 3,
    category_id: 1,
  },
  {
    id: 5,
    name: "orange",
    image: "/img/products/product-5.jpg",
    price: 1400,
    rating: 2,
    category_id: 1,
  },
  {
    id: 6,
    name: "tomato",
    image: "/img/products/product-6.jpg",
    price: 100,
    rating: 0,
    category_id: 1,
  },
  {
    id: 7,
    name: "orange",
    image: "/img/products/product-1.jpg",
    price: 100,
    rating: 2,
    category_id: 2,
  },
  {
    id: 8,
    name: "peal",
    image: "/img/products/product-4.jpg",
    price: 100,
    rating: 0,
    category_id: 2,
  },
  {
    id: 9,
    name: "tomato",
    image: "/img/products/product-5.jpg",
    price: 100,
    rating: 1,
    category_id: 1,
  },
  {
    id: 10,
    name: "tomato",
    image: "/img/products/product-7.jpg",
    price: 100,
    rating: 5,
    category_id: 1,
  },
]
export const categoriesData = [
  {
    id: 1,
    name: "Máy tính",
  },
  {
    id: 2,
    name: "Điện thoại",
  },
  {
    id: 3,
    name: "Laptop",
  },
  {
    id: 4,
    name: "Máy ảnh",
  },
  {
    id: 5,
    name: "Máy ảnh",
  },
  {
    id: 6,
    name: "Máy ảnh",
  },
  {
    id: 7,
    name: "Máy ảnh",
  },
  {
    id: 8,
    name: "Máy ảnh",
  },
  {
    id: 9,
    name: "Máy ảnh",
  },
]
export const recommendedProductsData = [
  {
    id: 1,
    name: "May choi game",
    image: "/img/products/product-1.jpg",
    price: 100,
    rating: 2,
    category_id: 1,
    colors: ["red", "green"],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 2",
    image: "/img/products/product-2.jpg",
    price: 200,
    discount: { percent: 30 },
    rating: 2,
    category_id: 1,
    colors: ["red", "yellow"],
    brand: "samsung",
  },
  {
    id: 1,
    name: "San pham 3",
    image: "/img/products/product-3.jpg",
    price: 10,
    discount: { percent: 30 },
    rating: 2,
    category_id: 1,
    colors: ["red"],
    brand: "iphone",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-4.jpg",
    price: 70,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: ["yellow"],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-5.jpg",
    price: 90,
    discount: { amount: 50 },
    rating: 2,
    category_id: 2,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 100,
    discount: { amount: 50 },
    rating: 2,
    category_id: 2,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 100,
    discount: { amount: 50 },
    rating: 2,
    category_id: 2,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 100,
    discount: { amount: 50 },
    rating: 2,
    category_id: 2,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 100,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 100,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 100,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 100,
    discount: { amount: 50 },
    rating: 2,
    category_id: 2,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 100,
    discount: { amount: 50 },
    rating: 2,
    category_id: 2,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 100,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 100,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 100,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 100,
    discount: { amount: 50 },
    rating: 2,
    category_id: 2,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 2,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 2,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 2,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 2,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 2,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 2,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
  {
    id: 1,
    name: "San pham 4",
    image: "/img/products/product-1.jpg",
    price: 80,
    discount: { amount: 50 },
    rating: 2,
    category_id: 1,
    colors: [],
    brand: "nokia",
  },
]
export const postsData = [
  {
    id: 1,
    image: "/img/blog/blog-1.jpg",
    title: "Mèo là loài động vật xộn lào nhất quả đất",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus id magnam explicabo illum laudantium fuga? Aspernatur ad excepturi laboriosam molestias nisi cumque quibusdam, possimus minima dolor recusandae libero quae nesciunt!",
    date: "1/12/2000",
    link: "/#",
    categories: ["dien thoai", "laptop"],
  },
  {
    id: 2,
    image: "/img/blog/blog-2.jpg",
    title: "Cho là loài động vật xộn lào nhất quả đất",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus id magnam explicabo illum laudantium fuga? Aspernatur ad excepturi laboriosam molestias nisi cumque quibusdam, possimus minima dolor recusandae libero quae nesciunt!",
    date: "1/12/2000",
    link: "/#",
    categories: ["dien thoai"],
  },
  {
    id: 2,
    image: "/img/blog/blog-3.jpg",
    title: "Cho là loài động vật xộn lào nhất quả đất",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus id magnam explicabo illum laudantium fuga? Aspernatur ad excepturi laboriosam molestias nisi cumque quibusdam, possimus minima dolor recusandae libero quae nesciunt!",
    date: "1/12/2000",
    link: "/#",
    categories: ["dien thoai", "may anh"],
  },
  {
    id: 2,
    image: "/img/blog/blog-4.jpg",
    title: "Cho là loài động vật xộn lào nhất quả đất",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus id magnam explicabo illum laudantium fuga? Aspernatur ad excepturi laboriosam molestias nisi cumque quibusdam, possimus minima dolor recusandae libero quae nesciunt!",
    date: "1/12/2000",
    link: "/#",
    categories: ["dien thoai"],
  },
  {
    id: 2,
    image: "/img/blog/blog-5.jpg",
    title: "Cho là loài động vật xộn lào nhất quả đất",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus id magnam explicabo illum laudantium fuga? Aspernatur ad excepturi laboriosam molestias nisi cumque quibusdam, possimus minima dolor recusandae libero quae nesciunt!",
    date: "1/12/2000",
    link: "/#",
    categories: ["dien thoai"],
  },
  {
    id: 2,
    image: "/img/blog/blog-1.jpg",
    title: "Cho là loài động vật xộn lào nhất quả đất",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus id magnam explicabo illum laudantium fuga? Aspernatur ad excepturi laboriosam molestias nisi cumque quibusdam, possimus minima dolor recusandae libero quae nesciunt!",
    date: "1/12/2000",
    link: "/#",
    categories: ["dien thoai"],
  },
  {
    id: 2,
    image: "/img/blog/blog-1.jpg",
    title: "Cho là loài động vật xộn lào nhất quả đất",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus id magnam explicabo illum laudantium fuga? Aspernatur ad excepturi laboriosam molestias nisi cumque quibusdam, possimus minima dolor recusandae libero quae nesciunt!",
    date: "1/12/2000",
    link: "/#",
    categories: ["dien thoai"],
  },
]
export const newProductsData = [
  {
    id: 1,
    name: "brocoli",
    image: "/assets/img/products/vegetable-1.jpg",
    price: 100,
    discount: { amount: 50 },
    rating: 2,
    weight: 150,
    category_id: 1,
  },
  {
    id: 2,
    name: "tomato",
    image: "/assets/img/products/vegetable-2.jpg",
    price: 13,
    discount: { percent: 20 },
    rating: 5,
    weight: 390,
    category_id: 1,
  },
  {
    id: 3,
    name: "pepper",
    image: "/assets/img/products/vegetable-3.jpg",
    price: 30,
    rating: 4,
    weight: 70,
    category_id: 1,
  },
  {
    id: 4,
    name: "banana",
    image: "/assets/img/products/vegetable-4.jpg",
    price: 500,
    discount: { amount: 220 },
    rating: 3,
    weight: 20,
    category_id: 1,
  },
  {
    id: 5,
    name: "orange",
    image: "/assets/img/products/vegetable-5.jpg",
    price: 1400,
    rating: 2,
    weight: 350,
    category_id: 1,
  },
  {
    id: 6,
    name: "tomato",
    image: "/assets/img/products/vegetable-6.jpg",
    price: 100,
    rating: 0,
    weight: 30,
    category_id: 1,
  },
  {
    id: 7,
    name: "orange",
    image: "/assets/img/products/fruit-1.jpg",
    price: 100,
    rating: 2,
    weight: 50,
    category_id: 2,
  },
  {
    id: 8,
    name: "peal",
    image: "/assets/img/products/fruit-2.jpg",
    price: 100,
    rating: 0,
    weight: 250,
    category_id: 2,
  },
  {
    id: 9,
    name: "tomato",
    image: "/assets/img/products/vegetable-2.jpg",
    price: 100,
    rating: 1,
    weight: 450,
    category_id: 1,
  },
  {
    id: 10,
    name: "tomato",
    image: "/assets/img/products/vegetable-3.jpg",
    price: 100,
    rating: 5,
    weight: 100,
    category_id: 1,
  },
]
